services:
  neurojit-ase:
    build: .
    image: neurojit-ase
    volumes:
      - ./data:/app/data
      - ./archive:/app/archive
    container_name: neurojit-ase
    command: ["scripts/reproduce.sh"]  # bash 대신 애플리케이션을 직접 실행하도록 설정
    stdin_open: true
    tty: true